version: '3'

services:
  spring:
    image: spring-boot
    build: ./backend
    expose:
      - ${BACKEND_PORT}
    container_name: ${BACKEND_NAME}
    depends_on:
      - mariadb
  
  react:
    image: react
    build: ./frontend
    depends_on:
      - spring
    expose:
      - ${FRONTEND_PORT}
    container_name: ${FRONTEND_NAME}

  nginx:
    image: nginx:1
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - spring
      - react
    environment:
      - BACKEND_NAME=${BACKEND_NAME}    
      - BACKEND_PORT=${BACKEND_PORT}
      - FRONTEND_NAME=${FRONTEND_NAME}
      - FRONTEND_PORT=${FRONTEND_PORT}
    
  mariadb:
    image: mariadb:10
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    expose:
      - 3306
    container_name: dbname
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=memodb
      - MARIADB_PORT=3306
      - MARIADB_HOST=dbname
